### PR TITLE
Fix compilation on parallel rustc

### PR DESCRIPTION
**Pull request by Zoxc**

### CODE REVIEW

**Comment by abonander** [comment]
@Zoxc what were the changes here? This PR has become so outdated that I can't tell what the original changes were.

**Comment by Zoxc** [comment]
Last commit has the changes: https://github.com/sfackler/rust-phf/pull/135/commits/7f2c56dec9cf3db75de51e01d2a199f57aa2dc4f

**Comment by abonander** [comment]
`phf_macros` was rewritten to be a proc_macro a long time ago, is this change even relevant anymore?

**Comment by Zoxc** [comment]
No. It's probably not relevant.

**Pull request closed without merging**
