### PR TITLE
Fix building with no_std

### LINKED ISSUE #189: Crate does not build in no_std
Seems like a regression in 645e23d - the `core` feature was renamed to `std`, but the `std` feature for `phf-shared` was not switched off by default in the `phf` Cargo.toml.

### PR DESCRIPTION
**Pull request by rjsberry**
Fixes #189

### CODE REVIEW

**Comment by rjsberry** [comment]
Hi @abonander, it seems to me the CI is failing due to an issue unrelated to this PR. Any ideas how we can work around this?

**Comment by neandrake** [comment]
I came across the CI failing as well and mentioned it in https://github.com/sfackler/rust-phf/pull/191#issuecomment-597423979. The issue looks to be related to a dependency requiring a newer version of rust than what CI is using to compile tests. My guess is that the CI needs updated to use rust 1.33 however I've not confirmed that it works with 1.33, only the current stable which is 1.41.1.

**Comment by abonander** [comment]
Thanks, I'll go ahead and merge this. Sorry for the delay.

**Comment by chemicstry** [comment]
Could we get a release with this patch? ❤️

**Comment by daniel5151** [comment]
@abonander any chance you could publish a new patch release `0.8.1` with this fix?

**Pull request merged**
