### PR TITLE
Remove PhfHash, use std::hash::Hash instead.

### PR DESCRIPTION
**Pull request by SimonSapin**
I started introducing a PhfHasher struct to make PhfHash more flexible for https://github.com/sfackler/rust-phf/issues/21#issuecomment-124632568 but quickly realized that this was redundant with `std::hash::Hasher`, and that `PhfHash` itself does little more than `std::hash::Hash`.

As a consequence of this change:

* `str` is hashed as *bytes, 0xff_u8* rather than just bytes, and `[u8]` is hashes as *length as usize, bytes* rather than just bytes. I don’t know if this affects anything. Tests still pass.
* A given type can not have a `PhfHash` impl and a `Hash` impl that behave differently anymore. I don’t know why they would want to do that.
* **This is a breaking change,** though perhaps not for most users. Users who use or implement `PhfHash` need to use `Hash` instead.

### CODE REVIEW

**Comment by sfackler** [comment]
We use `PhfHash` instead of `Hash` to make sure the hash is consistent when cross compiling. For example, when crossing from 64 bit to 32 bit, a `[u8]`'s ouput from `Hash` will change since the size field will change from 8 bytes to 4 bytes.

**Comment by sfackler** [comment]
Notably, see how the `PhfHash` implementation for `[u8]` differs from the others: https://github.com/sfackler/rust-phf/blob/master/phf_shared/src/lib.rs#L51.

It looks like I do need to be making sure the endianness is consistent for primitives, which isn't happening right now.

**Comment by SimonSapin** [comment]
I see. So what do you think of adding `PhfHasher` to allow hashing incrementally generated bytes?

**Comment by sfackler** [comment]
I'd be totally fine with that - it could probably be adjusted to have the exact same signature as Rust's `Hash`.

**Comment by sfackler** [comment]
How does this look? https://github.com/sfackler/rust-phf/commit/96ef156baae669b233673d6be2b96617ad48551e

**Comment by SimonSapin** [comment]
:+1:

**Comment by sfackler** [comment]
I think this PR can be closed now? Please reopen if not!

**Comment by SimonSapin** [comment]
Yes, sorry I forgot.

**Pull request closed without merging**
