### PR TITLE
Changed macros to work on stable

### PR DESCRIPTION
**Pull request by danielhenrymantilla**
Fixes https://github.com/sfackler/rust-phf/issues/106, although at the cost of requiring `lazy_static!`-like syntax.

### CODE REVIEW

**Comment by sfackler** [comment]
Nice! Rather than breaking back-compat, how about we add a new macro that handles the unstable-ness?

```rust
phf! {
    static MAP: phf::Map<&str, &str> = phf_map! {};
    static SET: phf::Set<&str> = phf_set! {};
    // ...
}
```

That way the (IMO cleaner) expression-based syntax is still there but we work on stable.

**Comment by dtolnay** [comment]
Would proc-macro-hack be sufficient for working on stable, without changing the input syntax?

**Comment by sfackler** [comment]
It seems like it should work, at least judging off the limitations listed in the README.

**Comment by danielhenrymantilla** [comment]
> Nice! Rather than breaking back-compat, how about we add a new macro that handles the unstable-ness?
> 
> ```rust
> phf! {
>     static MAP: phf::Map<&str, &str> = phf_map! {};
>     static SET: phf::Set<&str> = phf_set! {};
>     // ...
> }
> ```
> 
> That way the (IMO cleaner) expression-based syntax is still there but we work on stable.

It can be done too, but actually `proc-macro-hack` seems to be a simpler solution for the users of the library
___

Aside: @dtolnay do you have or plan on writing a blog post about the internals of `proc-macro-hack`?

**Comment by sfackler** [comment]
Yeah, let's go with proc-macro-hack.

**Comment by abonander** [comment]
Closed in favor of #149

**Pull request closed without merging**
