### PR TITLE
impl PhfHash for (...)

### PR DESCRIPTION
**Pull request by strake**

### CODE REVIEW

**Comment by sfackler** [comment]
It looks like there are some warnings caused by the upper case variables: https://travis-ci.org/sfackler/rust-phf/jobs/328542806

**Comment by sfackler** [comment]
Thanks!

**Comment by sfackler** [comment]
Out of curiosity, what are you using tuple keys for?

**Comment by strake** [comment]
Map from (key code, modifier) to action in a terminal emulator

**Comment by sfackler** [comment]
Does a match not optimize well for that use case?

**Comment by strake** [comment]
It might, but i'm generating the table from a static config file and this just seemed easier.

**Comment by sfackler** [comment]
Cool thanks for the info. For some background, I'm thinking about adjusting the API from a `Hash` based one to one that just passes a byte buffer. This will provide some more flexibility to look into approaches like gperf's, where it constructs a custom hash function that only looks at a minimal number of bytes required to make the hash unique. Unfortunately, this doesn't really work with composite types like tuples in a super easy way.

**Pull request merged**
